# Generated by Django 2.1.5 on 2019-12-27 07:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название баннера')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('short_description_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', stdimage.models.StdImageField(upload_to='banner_images/', verbose_name='Картинка для фона баннера')),
                ('number', models.SmallIntegerField(default=0, verbose_name='Порядок вывода')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
                'verbose_name': 'Баннер',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name_plural': 'Разделы',
                'verbose_name': 'Раздел',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Порядок вывода на сайт')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('description', models.CharField(max_length=100, verbose_name='Описание (например, "к.т.н.")')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй номер телефона (необязательно)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='ContactSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Порядок вывода отдела')),
                ('title', models.CharField(max_length=50, verbose_name='Название отдела')),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name_plural': 'Отделы (для контактов)',
                'verbose_name': 'Отдел',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('main_page_rotation', models.BooleanField(default=False, verbose_name='Включить в ротацию на главной')),
            ],
            options={
                'verbose_name_plural': 'Документы',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=80, verbose_name='Краткое название компании')),
                ('full_name', models.CharField(default='', max_length=80, verbose_name='Полное название компании')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй номер телефона (необязательно)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание, история создания')),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logotype', models.FileField(upload_to='partners_logotypes/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', stdimage.models.StdImageField(upload_to='post_images/', verbose_name='Картинка для публикации')),
                ('number', models.SmallIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name_plural': 'Фотографии',
                'verbose_name': 'Фотография',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок публикации')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок публикации')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткий текст')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробный текст')),
                ('main_picture', stdimage.models.StdImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Главная картинка публикации')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('mark_as_announcement', models.BooleanField(default=False, verbose_name='Отметить как анонс события')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Category')),
            ],
            options={
                'verbose_name_plural': 'Публикации',
                'verbose_name': 'Публикация',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name_plural': 'Тэги',
                'verbose_name': 'Тэг',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Post'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='mainapp.Tag'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ContactSubdivision'),
        ),
    ]
