# Generated by Django 2.1.5 on 2019-03-14 07:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='bla', verbose_name='Текст публикации'),
            preserve_default=False,
        ),
    ]
