# Generated by Django 2.1.5 on 2019-03-15 08:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='vkfjnvkjdf', verbose_name='Подробный текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок публикации'),
        ),
    ]
