# Generated by Django 2.1.5 on 2019-03-15 08:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190315_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Подробный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткий текст'),
        ),
    ]
