# Generated by Django 2.1.5 on 2019-08-14 06:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_photo_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('description', models.CharField(max_length=100, verbose_name='Описание (должность)')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Порядок вывода на сайт')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
            ],
            options={
                'verbose_name_plural': 'Документы',
                'verbose_name': 'Документ',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('logotype', models.FileField(upload_to='partners_logotypes/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name_plural': 'Партнеры',
                'verbose_name': 'Партнер',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name_plural': 'Тэги',
                'verbose_name': 'Тэг',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AddField(
            model_name='post',
            name='main_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='full_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Подробный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткий текст'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(to='mainapp.Tag'),
        ),
    ]
