# Generated by Django 2.1.5 on 2019-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190814_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.CharField(default='', max_length=50, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй номер телефона (необязательно)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Описание (например, "к.т.н.")'),
        ),
    ]
