# Generated by Django 2.1.5 on 2019-08-19 07:38

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190814_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название баннера')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('short_description_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', stdimage.models.StdImageField(upload_to='banner_images/', verbose_name='Картинка для фона баннера')),
                ('number', models.SmallIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name_plural': 'Баннеры',
                'verbose_name': 'Баннер',
            },
        ),
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=80, verbose_name='Краткое название компании')),
                ('full_name', models.CharField(default='', max_length=80, verbose_name='Полное название компании')),
                ('phone', models.CharField(default='', max_length=50, verbose_name='Номер телефона')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, null=True, verbose_name='Второй номер телефона (необязательно)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание, история создания')),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
